name: build ecp-ai

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build-docker-images:
    name: build ecp-ai
    runs-on: ubuntu-22.04-arm
    permissions: write-all

    steps:
    - uses: actions/create-github-app-token@v1
      id: generate-token
      with:
        app-id: ${{ vars.AUTH_APP_ID }}
        private-key: ${{ secrets.AUTH_APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
        repositories: |
          ecp-ai
          emqx-ai
          EMQX-Business-Critical
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ steps.generate-token.outputs.token }}
    # 拉取 https://github.com/emqx/ecp-ai 仓库
    - uses: actions/checkout@v4
      with:
        repository: emqx/ecp-ai
        ref: main
        path: ecp-ai
        token: ${{ steps.generate-token.outputs.token }}
    - uses: docker/setup-buildx-action@v3
    - uses: docker/setup-qemu-action@v3
      with:
          image: tonistiigi/binfmt:qemu-v7.0.0-28
    - name: Check latest image
      id: latest
      run: |
        echo "latest=false" >> $GITHUB_OUTPUT
        if echo "${{ github.ref_name }}" |egrep -q "^[0-9].[0-9].[0-9]$"; then
        echo "latest=true" >> $GITHUB_OUTPUT
        fi
    - name: Cusmoter image tag
      id: customer
      run: |
        tag="${GITHUB_REF##*/}"
        echo "tag=$tag" >> $GITHUB_OUTPUT
    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: ghcr.io/emqxecp/ecp-ai
        flavor: |
          latest=${{ steps.latest.outputs.latest }}
        tags: |
          type=raw,enable=${{ contains(github.ref_name, 'customer') }},value=${{ steps.customer.outputs.tag }}
          type=ref,event=branch,enable=${{ !contains(github.ref_name, 'customer') }}
          type=ref,event=pr,enable=${{ !contains(github.ref_name, 'customer') }}
          type=ref,event=tag,enable=${{ !contains(github.ref_name, 'customer') }}
          type=semver,pattern={{version}},enable=${{ !contains(github.ref_name, 'customer') }}
          type=semver,pattern={{major}}.{{minor}},enable=${{ !contains(github.ref_name, 'customer') }}
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.EMQXECP_GIT_TOKEN }}
    - name: Get platform
      id: platform
      run: |
        # Always support both amd64 and arm64 platforms
        # platform="linux/amd64,linux/arm64"
        platform="linux/amd64"
        echo "platform=$platform" >> $GITHUB_OUTPUT
    - name: Cleanup Disk Space
      run: |
        docker system prune --all --force
        sudo rm -rf /tmp/*
        sudo rm -rf /var/tmp/*
        sudo rm -rf /var/cache/apt/*
        sudo rm -rf /var/cache/debconf/*-old
        sudo rm -rf /var/lib/dpkg/*-old
        sudo rm -rf /var/log/*
        sudo rm -rf /var/cache/*
        echo "Disk cleanup completed."
    - name: Build image
      uses: docker/build-push-action@v3
      with:
        push: true
        load: ${{ contains(github.ref_name, 'customer') }}
        platforms: ${{ steps.platform.outputs.platform }}
        build-args: |
          GIT_TOKEN=${{ steps.generate-token.outputs.token }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ecp-ai/Dockerfile
        context: ecp-ai
        outputs: type=oci,dest=/tmp/ecp-ai.tar
