name: build trace-exchanger

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build-docker-images:
    name: build trace-exchanger
    runs-on: ubuntu-22.04-arm
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ github.token }}
    # 拉取 https://github.com/emqxecp/trace-exchanger 仓库
    - uses: actions/checkout@v4
      with:
        repository: emqxecp/trace-exchanger
        ref: main
        path: trace-exchanger
        fetch-depth: 0
        token: ${{ secrets.EMQXECP_GIT_TOKEN }}
    - name: Check latest image
      id: latest
      run: |
        echo "latest=false" >> $GITHUB_OUTPUT
        if echo "${{ github.ref_name }}" |egrep -q "^[0-9].[0-9].[0-9]$"; then
        echo "latest=true" >> $GITHUB_OUTPUT
        fi
    - name: Cusmoter image tag
      id: customer
      run: |
        tag="${GITHUB_REF##*/}"
        echo "tag=$tag" >> $GITHUB_OUTPUT
    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: ghcr.io/emqxecp/trace-exchanger
        flavor: |
          latest=${{ steps.latest.outputs.latest }}
        tags: |
          type=raw,enable=${{ contains(github.ref_name, 'customer') }},value=${{ steps.customer.outputs.tag }}
          type=ref,event=branch,enable=${{ !contains(github.ref_name, 'customer') }}
          type=ref,event=pr,enable=${{ !contains(github.ref_name, 'customer') }}
          type=ref,event=tag,enable=${{ !contains(github.ref_name, 'customer') }}
          type=semver,pattern={{version}},enable=${{ !contains(github.ref_name, 'customer') }}
          type=semver,pattern={{major}}.{{minor}},enable=${{ !contains(github.ref_name, 'customer') }}
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.EMQXECP_GIT_TOKEN }}
    - name: Cleanup Disk Space
      run: |
        docker system prune --all --force
        sudo rm -rf /tmp/*
        sudo rm -rf /var/tmp/*
        sudo rm -rf /var/cache/apt/*
        sudo rm -rf /var/cache/debconf/*-old
        sudo rm -rf /var/lib/dpkg/*-old
        sudo rm -rf /var/log/*
        sudo rm -rf /var/cache/*
        echo "Disk cleanup completed."
    - name: Build image
      uses: docker/build-push-action@v3
      with:
        push: true
        load: ${{ contains(github.ref_name, 'customer') }}
        build-args: |
          GIT_TOKEN=${{ secrets.CI_GIT_TOKEN }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: trace-exchanger/Dockerfile
        context: trace-exchanger